# fallback to provide the same functionallity as in CMake 3.14+
if(${CMAKE_VERSION} VERSION_LESS 3.14)
    macro(FetchContent_MakeAvailable NAME)
        string(TOLOWER "${NAME}" lcName)
        FetchContent_GetProperties(${lcName})
        if(NOT ${lcName}_POPULATED)
            FetchContent_Populate(${NAME})
            message(STATUS "Populated ${NAME}")
            # message(VERBOSE "${lcName}_SOURCE_DIR = ${${lcName}_SOURCE_DIR}")
            # message(VERBOSE "${lcName}_BINARY_DIR = ${${lcName}_BINARY_DIR}")
            if(EXISTS ${${lcName}_SOURCE_DIR}/CMakeLists.txt)
                add_subdirectory(${${lcName}_SOURCE_DIR} ${${lcName}_BINARY_DIR})
            endif()
        endif()
    endmacro()
endif()
